name: force_directed_graph
description: A package for creating force directed graphs.
version: 0.1.0
homepage: "https://github.com/jonaird/force_directed_graph"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.7.0 <4.0.0"

dependencies:
  vector_math: 
  collection: 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


