name: force_directed_graph
description: A package for displaying force directed graphs.
version: 0.1.1
homepage: "https://github.com/jonaird/force_directed_graph"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.7.0"

dependencies:
  vector_math: ^2.1.4
  collection: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


